// Synthesizable Verilog-2001 generation for circuits, FSMs and custom blocks, plus testbench generation.
(function () {
  const GV = (globalThis.GV = globalThis.GV || {});
  const { sanitize } = GV;

  const rng = (w) => (w > 1 ? `[${w - 1}:0] ` : '');
  const hex = (v, w) => `${w}'h${BigInt(v).toString(16)}`;

  function needsClock(project, name, seen = new Set()) {
    if (seen.has(name)) return false;
    seen.add(name);
    const circ = project.circuits[name];
    if (!circ) return false;
    return circ.components.some((c) => c.type === 'register' || c.type === 'counter' || c.type === 'fsm' ||
      (c.type === 'sub' && needsClock(project, c.props.circuit, seen)));
  }

  function resetBits(project) {
    const v = project.settings.verilog;
    const clk = sanitize(v.clock || 'clk'), rst = sanitize(v.reset || 'rst');
    const cond = v.resetActiveLow ? `!${rst}` : rst;
    const edge = v.resetStyle === 'async' ? `always @(posedge ${clk} or ${v.resetActiveLow ? 'negedge' : 'posedge'} ${rst})` : `always @(posedge ${clk})`;
    return { clk, rst, cond, edge };
  }

  class Writer {
    constructor(indent) { this.lines = []; this.ind = ' '.repeat(indent); }
    line(depth, s) { this.lines.push(this.ind.repeat(depth) + s); }
    blank() { this.lines.push(''); }
    text() { return this.lines.join('\n'); }
  }

  function header(project, w, what) {
    if (!project.settings.verilog.header) return;
    w.line(0, `// ${what}`);
    w.line(0, `// Generated by Graphical Verilog from project "${project.name}"`);
  }

  function portList(w, ports) {
    w.line(0, '(');
    ports.forEach((p, i) => w.line(1, p + (i < ports.length - 1 ? ',' : '')));
    w.line(0, ');');
  }

  // ---------- Custom expression modules ----------
  function genAssignModule(project, modName, def, warnings) {
    const ins = GV.parsePortSpec(def.inputs).map((p) => ({ name: p.name, w: p.width }));
    const outs = GV.parsePortSpec(def.outputs).map((p) => ({ name: p.name, w: p.width }));
    const prog = GV.compileAssigns(def.code, ins, outs, modName);
    const w = new Writer(project.settings.verilog.indent);
    header(project, w, `Custom block ${modName}`);
    w.line(0, `module ${modName}`);
    portList(w, [...ins.map((p) => `input  wire ${rng(p.w)}${p.name}`), ...outs.map((p) => `output wire ${rng(p.w)}${p.name}`)]);
    for (const a of prog.compiled) if (a.internal) w.line(1, `wire ${rng(a.w)}${a.lhs};`);
    const assigned = new Set(prog.compiled.map((a) => a.lhs));
    for (const a of prog.compiled) w.line(1, `assign ${a.lhs} = ${a.src.replace(/\s+/g, ' ')};`);
    for (const o of outs) if (!assigned.has(o.name)) { w.line(1, `assign ${o.name} = ${o.w}'d0;`); warnings.push(`${modName}: output ${o.name} is never assigned (tied to 0)`); }
    w.line(0, 'endmodule');
    return w.text();
  }

  // ---------- FSM ----------
  function genFsm(project, name, warnings) {
    const f = project.fsms[name];
    const modName = sanitize(name);
    const v = resetBits(project);
    const ind = project.settings.verilog.indent;
    const w = new Writer(ind);
    const ins = GV.parsePortSpec(f.inputs).map((p) => ({ name: p.name, w: p.width }));
    const outs = GV.parsePortSpec(f.outputs).map((p) => ({ name: p.name, w: p.width, def: p.def }));
    if (!f.states.length) throw new GV.SimError(`State machine ${name} has no states`);
    const sb = GV.fsmStateBits(f);
    const used = new Set();
    const sname = new Map();
    f.states.forEach((s) => {
      let n = 'S_' + sanitize(s.name).toUpperCase();
      while (used.has(n)) n += '_';
      used.add(n);
      sname.set(s.id, n);
    });
    const code = (i) => {
      if (f.encoding === 'onehot') return `${sb}'b${(1n << BigInt(i)).toString(2).padStart(sb, '0')}`;
      if (f.encoding === 'gray') return `${sb}'d${i ^ (i >> 1)}`;
      return `${sb}'d${i}`;
    };
    // Validate with the simulator's compiler; it throws on bad expressions.
    const sim = new GV.FsmSim(project, name);
    const internals = new Map();
    const collect = (prog) => prog.compiled.forEach((a) => { if (a.internal) internals.set(a.lhs, a.w); });
    sim.moore.forEach(collect);
    sim.trans.forEach((list) => list.forEach((t) => collect(t.actions)));

    header(project, w, `State machine ${name} (${f.encoding} encoding, ${f.states.length} states)`);
    w.line(0, `module ${modName}`);
    portList(w, [
      `input  wire ${v.clk}`, `input  wire ${v.rst}`,
      ...ins.map((p) => `input  wire ${rng(p.w)}${p.name}`),
      ...outs.map((p) => `output reg  ${rng(p.w)}${p.name}`),
      ...(f.exposeState ? [`output wire ${rng(sb)}state`] : []),
    ]);
    w.blank();
    f.states.forEach((s, i) => w.line(1, `localparam ${rng(sb)}${sname.get(s.id)} = ${code(i)};`));
    w.blank();
    w.line(1, `reg ${rng(sb)}state_r, state_nxt;`);
    for (const [n, wd] of internals) w.line(1, `reg ${rng(wd)}${n};`);
    if (f.exposeState) w.line(1, 'assign state = state_r;');
    w.blank();
    w.line(1, `${v.edge} begin`);
    w.line(2, `if (${v.cond}) state_r <= ${sname.get(f.reset)};`);
    w.line(2, 'else state_r <= state_nxt;');
    w.line(1, 'end');
    w.blank();
    w.line(1, 'always @(*) begin');
    w.line(2, 'state_nxt = state_r;');
    for (const o of outs) w.line(2, `${o.name} = ${o.def ? hex(GV.evalConst(o.def, o.w), o.w) : `${o.w}'d0`};`);
    for (const [n, wd] of internals) w.line(2, `${n} = ${wd}'d0;`);
    w.line(2, 'case (state_r)');
    for (const s of f.states) {
      w.line(3, `${sname.get(s.id)}: begin`);
      for (const a of sim.moore.get(s.id).compiled) w.line(4, `${a.lhs} = ${a.src.replace(/\s+/g, ' ')};`);
      const list = sim.trans.get(s.id) || [];
      let first = true;
      for (const tr of list) {
        const body = (d) => {
          w.line(d, `state_nxt = ${sname.get(tr.t.to)};`);
          for (const a of tr.actions.compiled) w.line(d, `${a.lhs} = ${a.src.replace(/\s+/g, ' ')};`);
        };
        if (!tr.cond) {
          if (first) body(4);
          else { w.line(4, 'else begin'); body(5); w.line(4, 'end'); }
          break;
        }
        w.line(4, `${first ? 'if' : 'else if'} (${tr.t.cond.trim().replace(/\s+/g, ' ')}) begin`);
        body(5);
        w.line(4, 'end');
        first = false;
      }
      w.line(3, 'end');
    }
    w.line(3, `default: state_nxt = ${sname.get(f.reset)};`);
    w.line(2, 'endcase');
    w.line(1, 'end');
    w.line(0, 'endmodule');
    const reachable = new Set([f.reset]);
    let grew = true;
    while (grew) { grew = false; for (const t of f.transitions) if (reachable.has(t.from) && !reachable.has(t.to)) { reachable.add(t.to); grew = true; } }
    for (const s of f.states) if (!reachable.has(s.id)) warnings.push(`${name}: state ${s.name} is unreachable from the reset state`);
    return w.text();
  }

  // ---------- Circuits ----------
  function genCircuit(project, name, ctx) {
    const circ = project.circuits[name];
    const modName = sanitize(name);
    const v = resetBits(project);
    const w = new Writer(project.settings.verilog.indent);
    const warnings = ctx.warnings;
    const clocked = needsClock(project, name);
    const comps = [...circ.components].filter((c) => GV.TYPES[c.type] && c.type !== 'note' && c.type !== 'probe').sort((a, b) => a.y - b.y || a.x - b.x);
    const ports = new Map(comps.map((c) => [c.id, GV.getPorts(c, project)]));

    // Port names
    const io = GV.circuitPorts(project, name);
    const taken = new Set([...io.ins, ...io.outs].map((p) => p.name));
    const seenPort = new Set();
    for (const p of [...io.ins, ...io.outs]) {
      if (seenPort.has(p.name)) throw new GV.SimError(`${name}: two ports are named '${p.name}'`);
      seenPort.add(p.name);
    }
    if (clocked) {
      for (const n of [v.clk, v.rst]) {
        if (taken.has(n)) throw new GV.SimError(`${name}: port '${n}' clashes with the implicit clock/reset name (rename it, or change the names in Settings)`);
        taken.add(n);
      }
    }
    const unique = (base) => { let n = base, k = 2; while (taken.has(n)) n = base + '_' + k++; taken.add(n); return n; };

    // Net name for every output pin.
    const net = new Map();
    const counters = {};
    const baseName = new Map();
    for (const c of comps) {
      const P = ports.get(c.id);
      if (c.type === 'input') { net.set(c.id + ':out', { name: sanitize(c.props.name), w: P.outs[0].w }); continue; }
      counters[c.type] = (counters[c.type] || 0) + 1;
      const base = c.label ? sanitize(c.label) : `${c.type}${counters[c.type]}`;
      baseName.set(c.id, c.label ? unique(base) : unique(base));
      for (const p of P.outs) {
        const n = P.outs.length === 1 ? baseName.get(c.id) : unique(baseName.get(c.id) + '_' + p.name);
        net.set(c.id + ':' + p.name, { name: n, w: p.w });
      }
    }
    const driver = new Map(circ.wires.map((wr) => [wr.to.c + ':' + wr.to.p, wr.from.c + ':' + wr.from.p]));

    const decls = [];
    const body = [];
    const adapters = [];
    const regNets = new Set();
    const labelOf = (c) => c.label || `${GV.TYPES[c.type].label} (${c.type === 'input' || c.type === 'output' ? c.props.name : c.id})`;

    // An identifier carrying exactly the pin width.
    const pin = (c, idx) => {
      const p = ports.get(c.id).ins[idx];
      const src = driver.get(c.id + ':' + p.name);
      const s = src && net.get(src);
      if (!s) {
        warnings.push(`${name}: ${labelOf(c)} input '${p.name}' is not connected (tied to 0)`);
        return `${p.w}'d0`;
      }
      if (s.w === p.w) return s.name;
      const n = unique(`${baseName.get(c.id) || 'n'}_${p.name}`);
      const expr = s.w > p.w ? `${s.name}[${p.w - 1}:0]` : `{{${p.w - s.w}{1'b0}}, ${s.name}}`;
      adapters.push(`wire ${rng(p.w)}${n} = ${expr};`);
      if (s.w > p.w) warnings.push(`${name}: ${labelOf(c)} input '${p.name}' is ${p.w} bit(s) but its wire carries ${s.w}; upper bits dropped`);
      return n;
    };
    // pin(), but guaranteed to be a plain identifier (literals get a named wire).
    const pinId = (c, idx) => {
      const e = pin(c, idx);
      if (/^[A-Za-z_]/.test(e)) return e;
      const p = ports.get(c.id).ins[idx];
      const n = unique(`${baseName.get(c.id) || 'n'}_${p.name}`);
      adapters.push(`wire ${rng(p.w)}${n} = ${e};`);
      return n;
    };
    const out = (c, p = null) => {
      const P = ports.get(c.id);
      return net.get(c.id + ':' + (p || P.outs[0].name)).name;
    };

    for (const c of comps) {
      const P = ports.get(c.id);
      const t = c.type;
      for (const p of P.outs) {
        if (t === 'input') continue;
        const n = net.get(c.id + ':' + p.name);
        const isReg = t === 'register' || t === 'counter';
        if (isReg) regNets.add(n.name);
        decls.push(`${isReg ? 'reg ' : 'wire'} ${rng(n.w)}${n.name};`);
      }
      const gateOp = GV.GATE_OPS[t];
      if (gateOp) {
        const terms = P.ins.map((_, i) => pin(c, i)).join(` ${gateOp} `);
        body.push(`assign ${out(c)} = ${['nand', 'nor', 'xnor'].includes(t) ? `~(${terms})` : terms};`);
        continue;
      }
      switch (t) {
        case 'input': break;
        case 'output': body.push(`assign ${sanitize(c.props.name)} = ${pin(c, 0)};`); break;
        case 'const': body.push(`assign ${out(c)} = ${hex(GV.evalConst(c.props.value || '0', P.outs[0].w), P.outs[0].w)};`); break;
        case 'not': body.push(`assign ${out(c)} = ~${pin(c, 0)};`); break;
        case 'mux': {
          const sel = pin(c, P.ins.length - 1);
          const n = P.ins.length - 1;
          const sw = P.ins[n].w;
          let e = pin(c, n - 1);
          for (let i = n - 2; i >= 0; i--) e = `(${sel} == ${sw}'d${i}) ? ${pin(c, i)} : ${e}`;
          body.push(`assign ${out(c)} = ${e};`);
          break;
        }
        case 'decoder': body.push(`assign ${out(c)} = ${P.outs[0].w}'d1 << ${pin(c, 0)};`); break;
        case 'slice': {
          const a = pinId(c, 0);
          const hi = c.props.lo + P.outs[0].w - 1;
          body.push(`assign ${out(c)} = ${P.ins[0].w === 1 ? a : hi === c.props.lo ? `${a}[${hi}]` : `${a}[${hi}:${c.props.lo | 0}]`};`);
          break;
        }
        case 'concat': body.push(`assign ${out(c)} = {${P.ins.map((_, i) => pin(c, i)).join(', ')}};`); break;
        case 'extend': {
          const a = pinId(c, 0), fw = P.ins[0].w, tw = P.outs[0].w;
          let e = a;
          if (tw > fw) e = c.props.sign ? `{{${tw - fw}{${fw === 1 ? a : `${a}[${fw - 1}]`}}}, ${a}}` : `{{${tw - fw}{1'b0}}, ${a}}`;
          body.push(`assign ${out(c)} = ${e};`);
          break;
        }
        case 'op': body.push(`assign ${out(c)} = ${pin(c, 0)} ${c.props.op} ${pin(c, 1)};`); break;
        case 'adder': body.push(`assign {${out(c, 'cout')}, ${out(c, 'sum')}} = ${pin(c, 0)} + ${pin(c, 1)} + ${pin(c, 2)};`); break;
        case 'register': {
          const q = out(c), wd = P.outs[0].w;
          body.push(`${v.edge} begin`);
          body.push(`  if (${v.cond}) ${q} <= ${hex(GV.evalConst(c.props.reset || '0', wd), wd)};`);
          body.push(`  else${c.props.enable ? ` if (${pin(c, 1)})` : ''} ${q} <= ${pin(c, 0)};`);
          body.push('end');
          break;
        }
        case 'counter': {
          const q = out(c), wd = P.outs[0].w;
          const rv = hex(GV.evalConst(c.props.reset || '0', wd), wd);
          body.push(`${v.edge} begin`);
          body.push(`  if (${v.cond}) ${q} <= ${rv};`);
          if (c.props.clear) body.push(`  else if (${pin(c, 1)}) ${q} <= ${rv};`);
          body.push(`  else if (${pin(c, 0)}) ${q} <= ${q} ${c.props.down ? '-' : '+'} ${wd}'d${Math.max(1, c.props.step | 0)};`);
          body.push('end');
          break;
        }
        case 'expr':
        case 'lib':
        case 'sub':
        case 'fsm': {
          let mod;
          if (t === 'expr') mod = ctx.exprModule(c);
          else if (t === 'lib') mod = ctx.libModule(c.props.lib);
          else if (t === 'sub') {
            if (!project.circuits[c.props.circuit]) throw new GV.SimError(`${name}: subcircuit '${c.props.circuit}' does not exist`);
            mod = sanitize(c.props.circuit);
          } else {
            if (!project.fsms[c.props.fsm]) throw new GV.SimError(`${name}: state machine '${c.props.fsm}' does not exist`);
            mod = sanitize(c.props.fsm);
          }
          const conns = [];
          if ((t === 'sub' && needsClock(project, c.props.circuit)) || t === 'fsm') conns.push(`.${v.clk}(${v.clk})`, `.${v.rst}(${v.rst})`);
          P.ins.forEach((p, i) => conns.push(`.${p.name}(${pin(c, i)})`));
          P.outs.forEach((p) => conns.push(`.${p.name}(${out(c, p.name)})`));
          body.push(`${mod} u_${baseName.get(c.id)} (`);
          conns.forEach((cn, i) => body.push(`  ${cn}${i < conns.length - 1 ? ',' : ''}`));
          body.push(');');
          break;
        }
      }
    }

    const ind = ' '.repeat(project.settings.verilog.indent);
    const fix = (s) => s.replace(/^( +)/, (m) => ind.repeat(m.length / 2));
    header(project, w, `Circuit ${name}`);
    w.line(0, `module ${modName}`);
    portList(w, [
      ...(clocked ? [`input  wire ${v.clk}`, `input  wire ${v.rst}`] : []),
      ...io.ins.map((p) => `input  wire ${rng(p.w)}${p.name}`),
      ...io.outs.map((p) => `output wire ${rng(p.w)}${p.name}`),
    ]);
    if (decls.length || adapters.length) w.blank();
    decls.forEach((d) => w.line(1, d));
    adapters.forEach((d) => w.line(1, d));
    if (body.length) w.blank();
    body.forEach((b) => w.line(1, fix(b)));
    w.line(0, 'endmodule');
    if (!io.ins.length && !io.outs.length) warnings.push(`${name}: circuit has no input or output ports`);
    return w.text();
  }

  function circuitOrder(project, top) {
    const order = [];
    const state = new Map();
    const visit = (n, path) => {
      if (state.get(n) === 'done') return;
      if (state.get(n) === 'busy') throw new GV.SimError('Subcircuit includes itself: ' + [...path, n].join(' → '));
      state.set(n, 'busy');
      const circ = project.circuits[n];
      if (circ) for (const c of circ.components) if (c.type === 'sub' && project.circuits[c.props.circuit]) visit(c.props.circuit, [...path, n]);
      state.set(n, 'done');
      order.push(n);
    };
    if (project.circuits[top]) visit(top, []);
    for (const n of Object.keys(project.circuits)) visit(n, []);
    return order;
  }

  // Generate every module. Returns { modules:[{name, kind, code}], text, warnings, errors }.
  function generateProject(project) {
    const warnings = [];
    const errors = [];
    const modules = [];
    const moduleNames = new Set();
    const claim = (n) => { let m = n, k = 2; while (moduleNames.has(m)) m = n + '_' + k++; moduleNames.add(m); return m; };
    Object.keys(project.circuits).forEach((n) => moduleNames.add(sanitize(n)));
    Object.keys(project.fsms).forEach((n) => moduleNames.add(sanitize(n)));

    const exprMods = new Map();
    const libMods = new Map();
    const ctx = {
      warnings,
      exprModule(c) {
        const key = JSON.stringify([c.props.inputs, c.props.outputs, c.props.code]);
        if (exprMods.has(key)) return exprMods.get(key);
        const mn = claim('blk_' + sanitize(c.props.title || 'expr'));
        exprMods.set(key, mn);
        modules.push({ name: mn, kind: 'block', code: genAssignModule(project, mn, c.props, warnings) });
        return mn;
      },
      libModule(lib) {
        if (libMods.has(lib)) return libMods.get(lib);
        const def = project.library[lib];
        if (!def) throw new GV.SimError(`Library block '${lib}' not found`);
        const mn = claim(sanitize(lib));
        libMods.set(lib, mn);
        modules.push({ name: mn, kind: 'library', code: genAssignModule(project, mn, def, warnings) });
        return mn;
      },
    };
    for (const n of Object.keys(project.fsms)) {
      try { modules.push({ name: sanitize(n), kind: 'fsm', code: genFsm(project, n, warnings) }); } catch (e) { errors.push(e.message); }
    }
    let order = [];
    try { order = circuitOrder(project, project.top); } catch (e) { errors.push(e.message); }
    for (const n of order) {
      try { modules.push({ name: sanitize(n), kind: 'circuit', code: genCircuit(project, n, ctx) }); } catch (e) { errors.push(e.message); }
    }
    const text = modules.map((m) => m.code).join('\n\n') + '\n';
    return { modules, text, warnings: [...new Set(warnings)], errors };
  }

  // Self-checking testbench from a recorded simulation history.
  function generateTestbench(project, circuitName, history) {
    const v = resetBits(project);
    const io = GV.circuitPorts(project, circuitName);
    const clocked = needsClock(project, circuitName);
    const tb = 'tb_' + sanitize(circuitName);
    const act = project.settings.verilog.resetActiveLow ? "1'b0" : "1'b1";
    const inact = project.settings.verilog.resetActiveLow ? "1'b1" : "1'b0";
    const L = [];
    L.push('`timescale 1ns/1ps');
    L.push(`// Self-checking testbench recorded from the Graphical Verilog simulator (${history.filter((h) => !h.reset).length} cycles).`);
    L.push(`module ${tb};`);
    L.push(`  reg ${v.clk} = 1'b0;`);
    L.push(`  reg ${v.rst} = ${act};`);
    io.ins.forEach((p) => L.push(`  reg ${rng(p.w)}${p.name} = ${p.w}'d0;`));
    io.outs.forEach((p) => L.push(`  wire ${rng(p.w)}${p.name};`));
    L.push('  integer errors = 0;');
    L.push('');
    const conns = [...(clocked ? [`.${v.clk}(${v.clk})`, `.${v.rst}(${v.rst})`] : []), ...io.ins.map((p) => `.${p.name}(${p.name})`), ...io.outs.map((p) => `.${p.name}(${p.name})`)];
    L.push(`  ${sanitize(circuitName)} dut (${conns.join(', ')});`);
    L.push('');
    L.push(`  always #5 ${v.clk} = ~${v.clk};`);
    L.push('');
    L.push('  initial begin');
    L.push(`    $dumpfile("${tb}.vcd");`);
    L.push(`    $dumpvars(0, ${tb});`);
    L.push(`    @(posedge ${v.clk}); #1 ${v.rst} = ${inact};`);
    let n = 0;
    for (const h of history) {
      if (h.reset) {
        L.push(`    // reset`);
        L.push(`    ${v.rst} = ${act}; @(posedge ${v.clk}); #1 ${v.rst} = ${inact};`);
        continue;
      }
      n++;
      L.push(`    // cycle ${h.cycle}`);
      const sets = io.ins.map((p) => `${p.name} = ${hex(h.inputs[p.name] ?? 0n, p.w)};`);
      if (sets.length) L.push('    ' + sets.join(' '));
      L.push('    #1;');
      for (const p of io.outs) {
        const e = hex(h.outputs[p.name] ?? 0n, p.w);
        L.push(`    if (${p.name} !== ${e}) begin errors = errors + 1; $display("cycle ${h.cycle}: ${p.name} = %h, expected %h", ${p.name}, ${e}); end`);
      }
      L.push(`    @(posedge ${v.clk}); #1;`);
    }
    L.push(`    if (errors == 0) $display("PASS: ${n} cycles match the Graphical Verilog simulation");`);
    L.push('    else $display("FAIL: %0d mismatches", errors);');
    L.push('    $finish;');
    L.push('  end');
    L.push('endmodule');
    return L.join('\n') + '\n';
  }

  Object.assign(GV, { generateProject, generateTestbench, needsClock });
})();
